### ISSUE TITLE
Nav icon missing on home screen on mobile when you scroll

### ISSUE THREAD

**Issue by harvzor** [OUBaC/OUBaC.github.io#22]
![navicon](https://cloud.githubusercontent.com/assets/7733459/10403938/38d594fe-6ec7-11e5-9774-7c4eefafe7cb.png)

A fix would be to add a class to the header which causes it to stick to the top of the page (giving the icon a background to be seen against).

**Comment by Tom-Johnston** [comment]
![screenshot_20151010-104914](https://cloud.githubusercontent.com/assets/9396007/10410542/becaff34-6f3c-11e5-83f6-a0c08b0d3db3.png)

I don't have this problem. The header should be fixed to the top using `position: fixed`. This is not supported in Opera mini and is buggy in Chrome and Safari on iOS 7.0-7.1 (http://caniuse.com/#search=position%3A%20fixed).

What browser are you running?

**Comment by harvzor** [comment]
It appears that the `.smaller` class does not get added to the `<header>` by the `scrollAdjuster()` function. This function seems to work on Chrome (both mobile and desktop), but not on any version of Firefox or IE.
