### ISSUE TITLE
Header too large on mobile

### ISSUE THREAD

**Issue by harvzor** [OUBaC/OUBaC.github.io#23]
The header is too large on mobile (it can take about a third of the space up on an iPhone 4 screen).

A class could be added to the header on scroll to make it minimize in height.

![header](https://cloud.githubusercontent.com/assets/7733459/10404011/bf153254-6ec7-11e5-8934-027cc6358c4a.png)

**Comment by Tom-Johnston** [comment]
I don't appear to have this problem.  The header should get smaller as you scroll before fixing at a minimum height. The scroll event is not supported by Opera Mini so the header will not get smaller when using this browser. 

What browser are you using?

![screenshot_20151010-105733](https://cloud.githubusercontent.com/assets/9396007/10410573/f033747e-6f3d-11e5-8900-ac860137b173.png)

**Comment by harvzor** [comment]
Fixing issue 22 should fix this bug too.
