### ISSUE TITLE
Impove URLs for SEO

### ISSUE THREAD

**Issue by harvzor** [OUBaC/OUBaC.github.io#25]
The URLs would be better if they didn't have ".html" appended to the end.

**Comment by harvzor** [comment]
It seems that GitHub hosting allows extensionless URLs, but a local dev environment (using `jekyll serve`) won't allow extensionless URLs. I'm having trouble trying to find a solution to this issue.

**Comment by Tom-Johnston** [comment]
I looked at doing this before but hit the problem you have just noted.
